<?php

use App\Models\Setup\Page;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class PageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pages = [
                        
            ['id' => 1, 'name' => 'Setup',	      'translate' => 'NAV.SETUP.SETUP',   "link" => '',	                            'parent_id' => 0,      'level'=> NULL,	    'type'=> 'group',   'icon'=> NULL,  'badge'=> NULL,     'isActive'=> 1,     'isDefault'=> 1,	'created_at'=> '2019-09-14 00:06:56',	'updated_at'=> '2019-09-14 00:06:56',	'created_by'=> 0,   'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>2,	'name' => 'MSS',	          'translate' => 'NAV.MSS.MSS',	 "link" => '',	                            'parent_id' => 0,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:14',	'updated_at'=> '2019-09-14 00:07:14',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>3,	'name' => 'Common Setup','translate' => 'NAV.SETUP.COMMON.COMMON',"link" => '',	                        'parent_id' => 1,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>4,	'name' => 'Security Setup',	  'translate' => NULL,	         "link" => '',	                            'parent_id' => 1,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>5,	'name' => 'Employee Setup',	  'translate' => NULL,	         "link" => NULL,                            'parent_id' => 1,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-24 11:45:20',	'updated_at'=> '2019-09-24 11:45:20',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>6,	'name' => 'Leave Approval Request','translate' => NULL,	     "link" => '/mss',                          'parent_id' => 2,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:30:06',	'updated_at'=> '2019-09-14 00:52:38',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>7,	'name' => 'Bank',	 'translate' => 'NAV.SETUP.COMMON.BANK', "link" => '/setup/banks',	                'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 04:07:15',	'updated_at'=> '2019-09-14 04:07:15',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>8,  'name' => 'ESS',	           'translate' => '',	         "link" => '/ess',	                        'parent_id' => 0,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 07:21:52',	'updated_at'=> '2019-09-14 07:21:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>9,	'name' => 'Page',	           'translate' => NULL,	         "link" => '/security-setup/pages',	        'parent_id' => 4,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>10,	'name' => 'Take Leave',	       'translate' => NULL,	         "link" => '/ess/take-leave',	            'parent_id' => 9,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-18 11:00:52',	'updated_at'=> '2019-09-18 11:00:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>11,	'name' => 'Approval Workflow', 'translate' => NULL,	         "link" => '/security-setup/approval-workflow','parent_id' => 4,	'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-18 11:00:52',	'updated_at'=> '2019-09-18 11:00:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>12,	'name' => 'Gender',	'translate' => 'NAV.SETUP.COMMON.GENDER',"link" => '/setup/genders',	            'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>13,	'name' => 'Permission',	       'translate' => NULL,	         "link" => '/setup/permission',	            'parent_id' => 4,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>14,	'name' => 'Position',	       'translate' => NULL,	         "link" => '/setup/positions',	            'parent_id' => 5,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>15,	'name' => 'Employee Divisions','translate' => 'NAV.SETUP.EMPLOYEE SETUP.EMPLOYEE DIVISIONS',	"link" => '/employee/employee-divisions','parent_id' => 5,'level'=> NULL,'type'=>'item','icon'=> NULL,'badge'=>NULL,'isActive'=> 1,'isDefault'=> 1,'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>16,	'name' => 'Employee Department','translate' => 'NAV.SETUP.EMPLOYEE SETUP.EMPLOYEE DEPARTMENT',	"link" => '/employee/employee-departments','parent_id' => 5,'level'=> NULL,'type'=>'item','icon'=>NULL,'badge'=>NULL,'isActive'=> 1,'isDefault'=> 1,'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>17,	'name' => 'Employee Unit',	   'translate' => 'NAV.SETUP.EMPLOYEE SETUP.EMPLOYEE UNIT',	"link" => '/employee/employee-units',	'parent_id' => 5,'level'=> NULL,'type'=>'item','icon'=>NULL,'badge'=>NULL, 'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>18,	'name' => 'Group Permission',  'translate' => NULL,	         "link" => '/security-setup/permission',	'parent_id' => 4,       'level'=> NULL,	'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>19,	'name' => 'Language', 'translate' => 'NAV.SETUP.COMMON.LANGUAGE',"link" => '/setup/languages',	        'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-24 11:31:52',	'updated_at'=> '2019-09-24 11:31:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>20,	'name' => 'Marital Status','translate' => 'NAV.SETUP.COMMON.MARITAL STATUS',	"link" => '/setup/marital-statuses','parent_id' => 3,'level'=> NULL,'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>21,	'name' => 'Payment Type','translate' => 'NAV.SETUP.COMMON.PAYMENT TYPE',"link" => '/setup/payment-type','parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>22,	'name' => 'Division',	 'translate' => 'NAV.SETUP.COMMON.DIVISION',"link" => '/setup/divisions',	    'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>23,	'name' => 'District',	 'translate' => 'NAV.SETUP.COMMON.DISTRICT',"link" => '/setup/districts',	    'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>24,	'name' => 'Hospital ',	 'translate' => '',	                 "link" => '/setup/hospital',	            'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>25,	'name' => 'Country','translate' =>'NAV.SETUP.COMMON.COUNTRY',"link" => '/setup/countries',	            'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>26,	'name' => 'Blood Group','translate'=>'NAV.SETUP.COMMON.BLOOD GROUP',"link" => '/setup/blood-groups',	'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>27,	'name' => 'Create User',	   'translate' => NULL,	         "link" => '/employee',	                    'parent_id' => 5,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> 'q',	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-26 13:07:52',	'updated_at'=> '2019-10-02 21:07:19',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>28,	'name' => 'Employee Shift',	   'translate' => 'NAV.SETUP.EMPLOYEE SETUP.EMPLOYEE SHIFT',"link" =>'/employee/employee-shift','parent_id' =>5,'level'=>NULL,'type'=>'item','icon'=>NULL, 'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>29,	'name' => 'Organogram',	       'translate' => NULL,	          "link" => '/employee/organogram',	        'parent_id' => 5,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-10-03 14:02:05',	'updated_at'=> '2019-10-03 14:02:05',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>30,	'name' => 'Overtime Approval Request','translate' => NULL,	  "link" => '/mss/overtime-approval-request','parent_id' => 2,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-10-05 14:54:43',	'updated_at'=> '2019-10-05 14:54:43',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>31,	'name' => 'Requisition',	   'translate' => NULL,	          "link" => '/ess/requisition',	            'parent_id' => 9,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-10-11 10:44:58',	'updated_at'=> '2019-10-11 10:44:58',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>32,	'name' => 'Roster',	           'translate' => 'Roster',	      "link" => '/mss/roster',	                'parent_id' => 2,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-18 11:00:52',	'updated_at'=> '2019-09-18 11:00:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>33,	'name' => 'Manual Attendance ','translate' => NULL,	          "link" => '/ess/manual-attendance',       'parent_id' => 	9,	'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> NULL,	                'updated_at'=> NULL,	                'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>34,	'name' => 'Dashboard',	       'translate' => NULL,	          "link" => '/ess/dashboard',	            'parent_id' => 9,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-08-22 07:42:01',	'updated_at'=> '2019-08-22 07:42:01',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>35,	'name' => 'Time Management',   'translate' => NULL,	          "link" => '/time-management',	            'parent_id' => 0,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 0,	    'isDefault'=> 0,	'created_at'=> '2019-10-15 17:58:30',	'updated_at'=> '2019-10-15 17:58:30',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>36,	'name' => 'Daily Attendance',  'translate' => NULL,	          "link" => '/time-management/daily-attendance','parent_id' => 66,	'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 0,	    'isDefault'=> 0,	'created_at'=> '2019-10-15 17:59:10',	'updated_at'=> '2019-10-15 17:59:10',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,    'deleted_at' => NULL],
            ['id' =>37,	'name' => 'Travel Setup',	   'translate' => NULL,	          "link" => '',	                            'parent_id' => 1,	    'level'=> NULL,	    'type'=> 'group',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>38,	'name' => 'Travel Types',	   'translate' => NULL,	          "link" => 'setup/travel/trip-type',	    'parent_id' => 68,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>39,	'name' => 'Travel Reason',	   'translate' => NULL,	          "link" => 'setup/travel/trip-reason',	    'parent_id' => 68,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>40,	'name' => 'Travel Mode',	   'translate' => NULL,	          "link" => 'setup/travel/trip-mode',       'parent_id' => 68,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>41,	'name' => 'Travel Purpose',	   'translate' => NULL,	          "link" => 'setup/travel/trip-purpose',	'parent_id' => 68,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,    'deleted_at' => NULL],
            ['id' =>42,	'name' => 'Travel Allowance',  'translate' => NULL,	          "link" => 'setup/travel/travel-allowance','parent_id' => 68,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-14 00:07:44',	'updated_at'=> '2019-09-14 00:07:44',	'created_by'=> 0,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>44,	'name' => 'E & C Setup',	   'translate' => NULL,	          "link" => '/engagement-and-culture-team',	'parent_id' => 1,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-08-22 07:42:01',	'updated_at'=> '2019-08-22 07:42:01',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>45,	'name' => 'Travel Request',	   'translate' => NULL,	          "link" => 'ess/request-travel',	        'parent_id' => 9,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-09-18 11:00:52',	'updated_at'=> '2019-09-18 11:00:52',	'created_by'=> 0,	'updated_by'=> 0,	'deleted_by'=> NULL,	'deleted_at' => NULL],
            ['id' =>46,	'name' => 'Relationship',	   'translate' => NULL,	          "link" => '/setup/relationship',	        'parent_id' => 3,	    'level'=> NULL,	    'type'=> 'item',	'icon'=> NULL,	'badge'=> NULL,	    'isActive'=> 1,	    'isDefault'=> 1,	'created_at'=> '2019-08-22 07:42:01',	'updated_at'=> '2019-08-22 07:42:01',	'created_by'=> 1,	'updated_by'=> 1,	'deleted_by'=> NULL,	'deleted_at' => NULL],
        ];
        Page::truncate()->insert($pages);
    }
}