<?php


namespace App\Facades;
use Illuminate\Support\Facades\Facade;

class EmailManager extends Facade{
    protected static function getFacadeAccessor() {
        return 'emailmanager'; // TODO: Change the autogenerated stub
    }
}
