<?php

namespace App\Models\EngagementAndCulture;

use App\Models\Base;
use App\Models\Employee\Employee;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmployeeEngagementAndCultureList extends Base
{
    function __construct()
    {
        parent::__construct($this);
    }

    use SoftDeletes;
    protected $table = 'employee_engagement_and_culture_lists';

    function employee(){
        return $this->hasOne('App\Models\Employee\Employee');
    }

    function getAll($resourcePerPage = 0, $orderBy = 'DESC')
    {
        $resources = EmployeeEngagementAndCultureList::orderBy('id', $orderBy )->get();
        $data = [];
        foreach ($resources as $resource) {
            $employee_name = Employee::where('id', $resource->enc_staff_id)->pluck('employeeName')->first();
            $data[] = [
                'id' => $resource->id,
                'staff_id' => $resource->enc_staff_id,
                'employee_name' => $employee_name,
                'created_at' => $resource->created_at,
                'updated_at' => $resource->updated_at
            ];
        }
        return ['data' => $data]; // TODO: Change the autogenerated stub
    }

    function storeResource($request)
    {
        $resource = new EmployeeEngagementAndCultureList();

        $resource->enc_staff_id = $request->employee;
        $resource->created_by = $request->created_by;
        $resource->updated_by = $request->updated_by;
        $resource->deleted_by = $request->deleted_by;
        $resource->softDelete = $request->softDelete;

        $resource->save();

        $employee = Employee::find($request->employee);
        return [
            'data' => [
                'id' => $resource->id,
                'staff_id' => $request->employee,
                'employee_name' => $employee->employeeName,
            ]
        ];
    }
}
